/* ############ INSERTION ############# */

INSERT INTO "user"
VALUES (DEFAULT, 'michel_dupont', 'Michel', 'Dupont'),
       (DEFAULT, 'jean_durant', 'Jean', 'Durant'),
       (DEFAULT, 'henri_petit', 'Henri', 'Petit'),
       (DEFAULT, 'gilbert_debois', 'Gilbert', 'Debois');

INSERT INTO location
VALUES (DEFAULT, 'Arles'),
       (DEFAULT, 'Montpellier'),
       (DEFAULT, 'Avignon');


INSERT INTO event (id, label, title, type, description, company_name, price, date, duration, address, zipcode, picture1,
                   picture2, picture3, location_id)
VALUES (DEFAULT,
        'Natural gardening', 'nature',
        'Discover the art of natural gardening and permaculture during a workshop led by Sylvie',
        'Take care of the soil by mulching and sowing green manure. Make your soil more alive by developing the activity of earthworms and micro-organisms through surface composting. Do not disturb the balance of an ecosystem, learn to decompact the earth without turning it over. Choose your seeds, produce your seeds. Design a favorable environment by using wasteland, by planting climbing plants or country hedges. Learn to observe the earth to find the best time to seed, plant and harvest.',
        'Natural industry', '30', '15/12/2020', '1 hour 30 minutes', '126 rue de Bagnolet', '34000',
        'http://www.image.workshop.tsukiru.com/gardening1.jpg',
        'http://www.image.workshop.tsukiru.com/gardening2.jpg',
        'http://www.image.workshop.tsukiru.com/gardening3.jpg',
        2),
       (DEFAULT,
        'Bungee jumping', 'sport',
        'Discover the joys of bungee jumping from the Alzon Viaduct for an unforgettable experience.',
        'Do you still dream of bungee jumping? Discover this thrilling activity from the Alzon Viaduct located in the Gard. From the viaduct, the site will enchant you with its beauty and its particularity, for a 50-meter bungee jump. Perfect for a first approach or for a two-person jump, in tandem. A unique pleasure not to be missed! So do not wait any longer, and come and try this wonderful experience. Our only advice: get started and don''t look down before… Bungee jumping is the ideal activity to offer to a loved one or for a bachelor party, especially since no physical or technical preparation is required beforehand.',
        'Ghislain & Roc', '50', '05/12/2020', '2 hours', 'Pont Raymond Charles', '34000',
        'http://www.image.workshop.tsukiru.com/elastique1.jpg',
        'http://www.image.workshop.tsukiru.com/elastique2.jpg',
        'http://www.image.workshop.tsukiru.com/elastique3.jpg',
        2),
       (DEFAULT,
        'Concert', 'concert',
        'Come and attend Eminem''s last concert for his album The Marshall Mathers LP',
        'The Marshall Mathers LP is rapper Eminem''s third studio album, if you count Infinite. This album was released in 2000 on Dr. Dre''s Aftermath Entertainment label. It won the Grammy Award for Best Rap Album in 2001. It has sold approximately 32 million copies worldwide1. Thanks to this album, Eminem also holds the record for sales in the United States on a week for a solo artist with 1.76 million sales. This record will be broken in 2015 by Adele. Eminem still holds the sales record in 1 week for a male solo artist. It is also a diamond record in the United States after having exceeded the mark of 11 million albums sold in the territory.',
        'Aftermath', '140', '01/01/2020', '1 hours 30', 'Arena de Montpellier', '34000',
        'http://www.image.workshop.tsukiru.com/rap1.jpg',
        'http://www.image.workshop.tsukiru.com/rap2.jpg',
        'http://www.image.workshop.tsukiru.com/rap3.jpg',
        2),
       (DEFAULT,
        'Outdoor climbing school 2020', 'sport',
        'La Vue Des Cimes offers climbing lessons with a state-certified instructor in the cliffs of southern France',
        'La Vue Des Cimes offers climbing lessons with a state-certified instructor, the concept is very simple: Come and discover the cliffs of the south of France for beginners as well as confirmed! Throughout the year, 25 trips lasting 3 hours are offered, taking place at more than 7 different climbing sites!',
        'La vue des cimes', '19', '29/11/2020', '4 hours', 'Montpellier', '34000',
        'http://www.image.workshop.tsukiru.com/climbing1.jpg',
        'http://www.image.workshop.tsukiru.com/climbing2.jpg',
        'http://www.image.workshop.tsukiru.com/climbing3.jpg',
        2),
       (DEFAULT,
        'Cinematographic projection', 'cinema',
        'Christopher Nolan''s new film is already available in your nearest cinema',
        'Tenet is a 2020 sci-fi thriller and film, written and directed by Christopher Nolan who also produced it with Emma Thomas. A UK-US co-production, it stars John David Washington, with Robert Pattinson, Elizabeth Debicki, Dimple Kapadia, Michael Caine and Kenneth Branagh. The plot follows a secret agent (played by John David Washington) who is forced to manipulate the flow of time to prevent the onset of World War III.Christopher Nolan spent more than five years writing the screenplay, having worked on Tenet''s central ideas for over a decade.',
        'Warner Bros.', '20', '02/01/2020', '2 Hours 30 ', '13 rue mangolres', '34000',
        'http://www.image.workshop.tsukiru.com/cinema1.png',
        'http://www.image.workshop.tsukiru.com/cinema2.png',
        'http://www.image.workshop.tsukiru.com/cinema3.png',
        2),
       (DEFAULT,
        'Driving course', 'sport',
        'Get behind the wheel of a Mustang GT and discover sporty driving on the Montpellier circuit',
        'The Mustang GT is a muscle car with unparalleled allure, an iconic vehicle of the Ford brand that will seduce you at first glance. If you are a fan of American sports cars, then do not hesitate any longer and come take the wheel of this legendary car to test its 421 horsepower engine on the circuit. You will not be disappointed !',
        'Pole Mecanic', '20', '28/01/2020', '2 Hours 30 ', '97 rue acridas', '34000',
        'http://www.image.workshop.tsukiru.com/race1.png',
        'http://www.image.workshop.tsukiru.com/race2.png',
        'http://www.image.workshop.tsukiru.com/race3.png',
        2),
       (DEFAULT,
        'Care & Massage', 'health',
        'Cryotherapy session in Montpellier',
        'Come and try an extraordinary session in the only whole body cryotherapy room in Montpellier! You will be greeted by a team of professionals trained at INSEP (National Institute of Sport, Expertise and Performance)',
        'Cryobox', '12', '15/01/2020', '1 hours', '74 Boulevard Haussmann', '34000',
        'http://www.image.workshop.tsukiru.com/cryo1.jpg',
        'http://www.image.workshop.tsukiru.com/cryo2.jpg',
        'http://www.image.workshop.tsukiru.com/cryo3.jpg',
        2),
       (DEFAULT,
        'Yoga', 'health',
        'Yoga & Essential Oils session in a hanging garden',
        'You will be welcomed for a workshop lasting 3:30, led by Sylvie from 10 a.m. to 1:30 p.m. You will have access to a room to change and all the necessary equipment for the activity is provided. In a group of no more than 12 people, you will start your yoga session, built by Sylvie, certified in Ayurvedic Medicine and Yoga. Depending on the energy center you want to stimulate, you will use different essential oils. These oils are organic and distilled by small producers. To complete this experience, Sylvie offers you a vegetarian plate made up of vegetables from the garden and a smoothie of fresh seasonal fruits.',
        'Sylvie', '12', '10/01/2020', '2 hours', '126 rue de Bagnolet', '34000',
        'http://www.image.workshop.tsukiru.com/yoga1.jpg',
        'http://www.image.workshop.tsukiru.com/yoga2.jpg',
        'http://www.image.workshop.tsukiru.com/yoga3.jpg',
        2)



INSERT INTO keyword
VALUES (DEFAULT, 'nature', 1),
       (DEFAULT, 'gardening', 1),
       (DEFAULT, 'permaculture', 1),

       (DEFAULT, 'bungee', 2),
       (DEFAULT, 'jumping', 2),

       (DEFAULT, 'eminem', 3),
       (DEFAULT, 'rap', 3),
       (DEFAULT, 'concert', 3),

       (DEFAULT, 'climbing', 4),
       (DEFAULT, 'sport', 4),
       (DEFAULT, 'outdoor', 4),

       (DEFAULT, 'cinema', 5),
       (DEFAULT, 'eolan', 5),
       (DEFAULT, 'pattinson', 5),
       (DEFAULT, 'debicki', 5),
       (DEFAULT, 'kapadia', 5),
       (DEFAULT, 'caine', 5),
       (DEFAULT, 'branagh', 5),

       (DEFAULT, 'course', 6),
       (DEFAULT, 'driving', 6),
       (DEFAULT, 'mustang', 6),
       (DEFAULT, 'ford', 6),

       (DEFAULT, 'massage', 7),
       (DEFAULT, 'cryotherapy', 7),
       (DEFAULT, 'care', 7),

       (DEFAULT, 'oils', 8),
       (DEFAULT, 'yoga', 8)

